{"pages":[],"posts":[{"title":"Hello World","text":"Welcome to Hexo! This is your very first post. Check documentation for more info. If you get any problems when using Hexo, you can find the answer in troubleshooting or you can ask me on GitHub. Quick StartCreate a new post$ hexo new \"My New Post\" More info: Writing Run server$ hexo server More info: Server Generate static files$ hexo generate More info: Generating Deploy to remote sites$ hexo deploy More info: Deployment","link":"/2018/01/15/hello-world/"},{"title":"GCS API 403 caller has no permission","text":"에러 : 403 caller has no error.GCS 사용하다가 마주친 에러 Solution 1 : 결제 에러 관련 bucket을 새로 만들어본다. 조회 명령어 gsutil ls gs://my-awesome-bucket bucket 새로 생성 gsutil mb -l us-east1 gs://my-awesome-bucket/ Solution 2 : 권한 에러 관련 공개로 돌려버리면 된다. all users를 추가하면 된다.","link":"/2019/02/14/error_set/google_cloud_storage_error/"},{"title":"python encoding error","text":"에러 메세지 : UnicodeDecodeError: ‘utf-8’ codec can’t decode byte 0xff in position 0: invalid 해결 방법 : encoding 부분을 utf-8에서 utf-16으로 바꿔주니까 된다. ( python3 기준 ) 예시 코드 # -*- coding: utf-8 -*-:import csvf = open('1_50000.csv', 'r', encoding='utf-16')rdr = csv.reader(f)for line in rdr: print(line)f.close()","link":"/2019/03/06/error_set/python_encoding_error/"},{"title":"pycharm java_home error","text":"에러 : Pycharm에 JAVA_HOME이 설정되어 있지 않다. 에러 원인 : Jpype가 설치되어 있지 않았고 JAVA_HOME이 설정 되어있지 않아서 에러가 발생했다. 해결 방법 JPype1-py3을 pycharm setting에 들어가서 설치해준다.위에 것을 설치해도 에러가 발생한다면 JAVA_HOME이 설정되어 있지 않아서이다. 시스템 변수에 JAVA_HOME을 추가해주었더니 실행이 되었다. 참고 URLhttps://mainia.tistory.com/5667","link":"/2019/02/01/error_set/pycharm_java_home_error/"},{"title":"Google Speech API 아무것도 출력이 되지 않는 에러","text":"원인아래 코드의 sample_rate_hertz가 일치하지 않아서 그렇다.ffmpeg를 사용해 동영상 확장자를 변환할 때 맞춰주어야 한다. 해결방법 ffmpeg로 변환을 시킨다. sample_rate_hertz가 16000으로 설정했기 때문에 변활시킬 때 16000으로 바꿔주어야 한다. ffmpeg -i audio_file.mp4 -acodec pcm_s16le -ac 1 -ar 16000 audio_file.wav 예제 코드 def transcribe_file(speech_file): \"\"\"Transcribe the given audio file.\"\"\" from google.cloud import speech from google.cloud.speech import enums from google.cloud.speech import types client = speech.SpeechClient() with io.open(speech_file, 'rb') as audio_file: content = audio_file.read() audio = types.RecognitionAudio(content=content) config = types.RecognitionConfig( encoding=enums.RecognitionConfig.AudioEncoding.LINEAR16, sample_rate_hertz=16000, language_code='ko-KR') response = client.recognize(config, audio) print(\"test2\") # Each result is for a consecutive portion of the audio. Iterate through # them to get the transcripts for the entire audio file. for result in response.results: print(\"test3\") # The first alternative is the most likely one for this portion. print(u'Transcript: {}'.format(result.alternatives[0].transcript))speech_file = \"audio_file.wav\"transcribe_file(speech_file)","link":"/2019/02/25/error_set/google_speech_api_error/"},{"title":"pandas No module named 'pandas.core.internals.managers'","text":"에러 메세지 : ModuleNotFoundError: No module named ‘pandas.core.internals.managers’; ‘pandas.core.internals’ is no 발생 원인 : A컴퓨터에서 잘 작동했던 파이썬 코드를 B컴퓨터에서 실행시키니 저 error가 계속 발생했다.처음에는 pandas 환경과 Python 버전 환경이 달라서 발생한 줄 알았다.그래서 환경을 똑같이 맞추어줬는데도 계속 에러가 발생했다.일단 에러 발생 부분을 보니 pickle.load() 하는 부분에서 에러가 발생했다.​ 해결 방법 : 결국 해결한 방법은 A 컴퓨터에서 pickle 파일 만들 때 pandas.DataFrame으로 넣지 않고 pandas.to_dict()로 바꿔서 파일을 만들었다.B 컴퓨터에서 pickle 파일 불러오고 dict 파일을 pandas.DataFrame으로 넣어서 해결했다.pickle 파일에 데이터 넣을 때 함부로 넣으면 안 되나 보다.","link":"/2019/04/07/error_set/pandas_error/"},{"title":"tensorflow 'drop_remainder' error","text":"에러 메세지 : TypeError: batch() got an unexpected keyword argument ‘drop_remainder’ 에러 원인 : Tensorflow 버전이 업그레이드 되면서 run_classifier.py의 코드가 수정되었다. 해결 방법 : runclassfier.py 파일에서 drop_remainder 코드를 제거해줘야 한다.","link":"/2019/04/08/error_set/tensorflow_error/"},{"title":"Loaded runtime CuDNN library 7101","text":"에러 메세지 : Loaded runtime CuDNN library: 7101 (compatibility version 7100) but source was compiled with 7003 (c 에러 원인 : tensorflow-gpu가 돌아가는 환경설정이 CUDA Toolkit 버전과 cuDNN 버전이 호환되지가 않아서 발생한 문제이다. 해결 방법 : Toolkit은 9.0 cuDNN은 7.0.5로 호환해주니 해결되었다.","link":"/2019/04/07/error_set/tensorflow_gpu_error/"},{"title":"php exec error","text":"에러 PHP에서 Python 스크립트 파일을 실행시켰다. Python 스크립트 파일에는 pytube를 이용해 영상을 다운받는 코드가 있었다. 하지만 download 가 되지 않는 문제가 있었다. 에러 원인 PHP에서 exec를 실행하면 www-data 일반 유저의 권한으로 해당 스크립트 파일을 실행시킨다.일반 유저의 권한으로는 파일 읽기 쓰기가 되지 않기 때문에 에러가 났었다. 해결방법 해당 파일들의 권한을 chmod 777이거나 쓰기 가능할 정도로 변경해주면 해결 가능하다.우선적으로 sudo 권한 아닐 때 실행시켜보면 에러 잡을 수 있다. 생각해봐야 할 것 근데 일반 서비스에서는 이렇게 함부로 권한 남발하면 안되는데….고민을 해봐야 할 문제이다. 참고 URL http://blog.naver.com/PostView.nhn?blogId=kkyy3402&amp;logNo=221284921252&amp;categoryNo=0&amp;parentCategoryNo=0&amp;viewDate=¤tPage=1&amp;postListTopCurrentPage=1&amp;from=postView​ http://blog.naver.com/PostView.nhn?blogId=anducher&amp;logNo=130033390734&amp;widgetTypeCall=true","link":"/2019/02/07/error_set/php_exec_error/"},{"title":"Scrapy AttributeError module 'lib' has no attribute 'Cryptography_HAS_SSL_ST","text":"에러 메세지 : AttributeError module ‘lib’ has no attribute ‘Cryptography_HAS_SSL_ST 원인 : Scrapy 설치하고 실행하려는데 에러가 발생했었다.찾아보니까 pyOpenSSL 문제인 것 같다.그냥 install 하나 해주니까 해결되었다. 해결방법 pip3 install pyOpenSSL==0.15.1","link":"/2019/02/26/error_set/scrapy_error/"},{"title":"Tensorflow RuntimeError Missing implementation that supports loader","text":"에러 메세지 : RuntimeError: Missing implementation that supports: loader(*(‘/tmp/tfhub_modules/mobilenet_module’,) 해결 방법 : loader 뒤에 뜨는 에러메세지 경로에 들어가서 tf_hub 파일을 지워주고 다시 실행시키니 작동하였다.이게 갑자기 어느 순간에 에러가 발생하는데… 왜 발생하는지는 모르겠다.그래도 해결방법이 단순하다. 참고 URLhttps://stackoverflow.com/questions/54029556/how-to-fix-runtimeerror-missing-implementation-that-supports-loader-when-cal","link":"/2019/04/04/error_set/tensorflow_hub_error-1/"},{"title":"tensorflow version error","text":"에러 메세지 : Only call softmax_cross_entropy_with_logits with named argument 에러 원인 : 텐서플로우가 1.x 대로 업그레이드 되면서 생긴 문제이다.함수 사용할 때 이미지와 같이 parameter를 구체적으로 표시해주어야 한다. 해결 방법 : labels 와 logits를 붙여주어야 한다.","link":"/2019/01/31/error_set/tensorflow_version_error-1/"},{"title":"Ubuntu E Problem executing scripts","text":"Error : Ubuntu E: Problem executing scripts APT우분투에서 apt-get 사용하다 발생한 error Solution sudo apt-get remove libappstream3 쉽게 해결된다.","link":"/2019/02/24/error_set/ubuntu_error/"},{"title":"tensorflow version error","text":"에러 메세지 : TypeError: Expected int32, got list containing Tensors of type _Message instead. 에러 원인 : Tensorflow가 1.x 대로 업그레이드 되면서 tf.concat의 input이 달라져서 생기는 문제이다. 이미지와 같이 수정해준다. 해결 방법 : parameter 위치만 바꿔주면 된다.","link":"/2019/01/31/error_set/tensorflow_version_error-2/"},{"title":"Tensorflow ImportError cannot import name 'regex_replace'","text":"해결 방법 : ELMo 사용하려고 Tensorflow Hub를 설치하고 실행시켜보니 위에 error 발생!처음에 0.3 버전으로 설치했는데…혹시나 해서 버전 0.2로 낮춰서 해보니 실행이 되었다…","link":"/2019/03/27/error_set/tensorflow_hub_error/"},{"title":"tensorflow version error","text":"에러 메세지 : batch() got an unexpected keyword argument ‘drop_remainder’ 에러 원인 : Tensorflow 버전이 업그레이드 되면서 run_classifier.py의 drop_remainder 파라미터가 없어졌다. 해결 방법 : runclassfier.py 파일에서 drop_remainder 코드를 제거해줘야 한다.","link":"/2019/04/08/error_set/tensorflow_version_error/"},{"title":"SSH 접속","text":"가장 기본적인 3306 포트 여는 방법 1.openssh를 설치해준다.apt-get install openssh-server 2. 설정파일을 바꾸어준다./etc/ssh/sshd_config 파일의 PermitRootLogin 부분을 yes로 만들어준다. 3. 비밀번호를 설정해준다.root 비밀번호가 처음에는 아마 설정 안되어 있기 때문에 설정해준 다음 접속한다. sudo passwd root 4. ssh를 재시작한다.sudo service ssh start ! 번외근데 최근에 ubuntu 18 버전으로 설치하고 openssh-server install 했는데 sshd_config 파일이 전부 주석처리 되어 있는 경우가 있었다. 결국은 해결 못 하고 16.04버전으로 했는데… 이럴 경우에 어떻게 해야 할지 좀 찾아봐야 겠다.","link":"/2019/01/15/setting/ssh_connect/"},{"title":"tensorflow version error","text":"가장 기본적인 3306 포트 여는 방법 1. mysql 폴더로 이동cd /etc/mysql/ 2. mysql.conf에서 mysql.cnf를 들어간다.vi mysql.conf.d 3. bind-address = 127.0.0.1 부분을 주석처리한다.# bind-address = 127.0.0.1 4. mysql 들어가서 설정을 바꿔준다.grant all privileges on *.* to 'root'@'%' identified by '비밀번호';flush privileges; 5. mysql restart를 한다.sudo /etc/init.d/mysql restart 6. 테스트 해본다.mysql -h \"IP주소\" -P 3306 -u root -p cf. 이래도 안되면은 방화벽을 검사해봐야 한다.","link":"/2019/01/15/setting/ubuntu_open_port/"}],"tags":[{"name":"google cloud","slug":"google-cloud","link":"/tags/google-cloud/"},{"name":"python","slug":"python","link":"/tags/python/"},{"name":"encoding","slug":"encoding","link":"/tags/encoding/"},{"name":"pycharm","slug":"pycharm","link":"/tags/pycharm/"},{"name":"java","slug":"java","link":"/tags/java/"},{"name":"google speech api","slug":"google-speech-api","link":"/tags/google-speech-api/"},{"name":"pandas","slug":"pandas","link":"/tags/pandas/"},{"name":"pickle","slug":"pickle","link":"/tags/pickle/"},{"name":"tensorflow","slug":"tensorflow","link":"/tags/tensorflow/"},{"name":"tensorflow gpu","slug":"tensorflow-gpu","link":"/tags/tensorflow-gpu/"},{"name":"php","slug":"php","link":"/tags/php/"},{"name":"exec","slug":"exec","link":"/tags/exec/"},{"name":"scrapy","slug":"scrapy","link":"/tags/scrapy/"},{"name":"tensorflow hub","slug":"tensorflow-hub","link":"/tags/tensorflow-hub/"},{"name":"elmo","slug":"elmo","link":"/tags/elmo/"},{"name":"ubuntu","slug":"ubuntu","link":"/tags/ubuntu/"},{"name":"drop_remainder","slug":"drop-remainder","link":"/tags/drop-remainder/"},{"name":"port","slug":"port","link":"/tags/port/"}],"categories":[{"name":"Error","slug":"Error","link":"/categories/Error/"},{"name":"setting","slug":"setting","link":"/categories/setting/"}]}